# Site settings
title: HEAD BLOG
tagline: Блог разработчиков...
email: hello@lead4crm.ru
description: > # this means to ignore newlines until "baseurl:"
  Салют! Вероятно вам стало интересно почитать наш блог, узнавая
  новости и различные полезности, прямо из первых рук и еще очень горячие. 
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://blog.lead4crm.ru" # the base hostname & protocol for your site
default_locate: "ru_RU"
logourl: /assets/images/logo.png # Site logo
author: "Главный хомяковый разработчик"
author_thumbnail: "/assets/images/avatar.jpg" # Author avatar
# Theme customization - please change from the defaults!
theme:
  # Color for sidebar bar, links, etc
  highlight_color: "#8d81ac" #205081" # "#272935"
  # Social media links, leave blank to ignore
  social: 
    github: LimyDesign
    # twitter: gayanvirajith
    facebook: lead4crm
    gplus: +lead4crmru
    # dribble: gayanvirajith
    # pinterest: gayanvirajith

  # Enable share buttons on post footer
  show_share_buttons: true

  # Show author picure, name and social links on post footer
  show_author_info: true

  # Disqus comments manager - shortname
  disqus_shortname: lead4crm

  # Google Analytics/Webmaster key, leave blank to ignore
  google_analytics_key: UA-28496970-6
  google_webmaster_key: BSrHLcEMpzDlCLB-uu5N24s8UD0eiinlsY6PqC7T3JU

# Build settings
markdown: kramdown

# Permalinks
permalink:        pretty

# Pagination config
paginate: 5

# Files/Folders to be excluded from generated _site folder
exclude: 
  - CNAME
  - Gemfile
  - Rakefile
  - README.md
  - .gitignore
  - .sass-cache
  - Gemfile.lock

# Sass conversion configs
sass:
  sass_dir: assets/css/_sass
  style: :compressed


# Add Jekyll plugin
gems:
  - jemoji
  - jekyll-sitemap